apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  mongo_uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvZWNvbW1lcmNl  # base64 encoded value of 'mongodb://18.188.82.20:27017'
  mysql_user_password: TWFkZWVwQG15c3Fs  # base64 encoded value of 'admin1237@'
  mysql_payment_password: TWFkZWVwQG15c3Fs  # base64 encoded value of 'admin1237@'
