apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  mongo_uri: bW9uZewe29kYjovLzEwewfw4LjE4OCffef4yMjcwMTc=  # replace with your mongo_uri encoded by base64
  mysql_user_password: YwerWRtassfsffreW4xMjM3wfQ==  # replace with your password encoded by base64
  mysql_payment_password: weWRtaWsfdsffsdfsd4xMjfrf3Q==  # replace with your password encoded by base64
