apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  mongo_uri: bW9uZ29kYjovLzE4LjE4OC44Mi4yMDoyNzAxNw==  # base64 encoded value of 'mongodb://18.188.82.20:27017'
  mysql_user_password: YWRtaW4xMjM3QA==  # base64 encoded value of 'admin1237@'
  mysql_payment_password: YWRtaW4xMjM3QA==  # base64 encoded value of 'admin1237@'
